export const browserCoreExamples = [
  "traversalai browser status",
  "traversalai browser start",
  "traversalai browser stop",
  "traversalai browser tabs",
  "traversalai browser open https://example.com",
  "traversalai browser focus abcd1234",
  "traversalai browser close abcd1234",
  "traversalai browser screenshot",
  "traversalai browser screenshot --full-page",
  "traversalai browser screenshot --ref 12",
  "traversalai browser snapshot",
  "traversalai browser snapshot --format aria --limit 200",
  "traversalai browser snapshot --efficient",
  "traversalai browser snapshot --labels",
];

export const browserActionExamples = [
  "traversalai browser navigate https://example.com",
  "traversalai browser resize 1280 720",
  "traversalai browser click 12 --double",
  'traversalai browser type 23 "hello" --submit',
  "traversalai browser press Enter",
  "traversalai browser hover 44",
  "traversalai browser drag 10 11",
  "traversalai browser select 9 OptionA OptionB",
  "traversalai browser upload /tmp/traversalai/uploads/file.pdf",
  'traversalai browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "traversalai browser dialog --accept",
  'traversalai browser wait --text "Done"',
  "traversalai browser evaluate --fn '(el) => el.textContent' --ref 7",
  "traversalai browser console --level error",
  "traversalai browser pdf",
];
